cargo-features = ["strip"]

[package]
name = "ntp"
version = "0.1.0"
edition = "2021"

[dependencies.chrono]
version = "0.4"
features = ["unstable-locales"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"